version: '3.3'
services:
  db:
    container_name: db
    image: db_amemiya:20190407
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: task_management
      MYSQL_USER: hoge
      MYSQL_PASSWORD: pass
    ports:
    - "3306:3306"
    volumes:
    - db-data:/var/lib/mysql
  app:
    container_name: app
    #build:
    #  context: .
    #  dockerfile: .docker/rails/Dockerfile
    image: task_application_ruby_app:20190418
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rdebug-ide --host 0.0.0.0 --port 1234 --dispatcher-port 26162 -- bin/rails s"
    ports:
    - "3000:3000"
    - "1234:1234"
    volumes:
    - .:/myapp
    - bundle-data1:/usr/local/bundle
    environment:
      RAILS_ENV: development
    env_file: .env.dev
    links:
    - db
    - smtp
    stdin_open: true
    tty: true
  smtp:
    container_name: smtp
    image: task_application_ruby_smtp:20190418
    #build: .docker/mailcatcher/
    ports:
      - "1080:1080"
      - "1025:1025"
  chrome:
    container_name: chrome
    image: task_application_ruby_chrome:20190418
    #build: .docker/selenium/
    links:
    - app
    ports:
    - 4444:4444
    - 5900:5900
volumes:
  db-data:
    external: true
  ## ここに関しては、アプリ毎に分けたほうが良い
  bundle-data1:
    external: true
