version: '3.3'
services:
  db:
    image: db_amemiya:20190407
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: task_management
      MYSQL_USER: hoge
      MYSQL_PASSWORD: pass
    ports:
    - "3306:3306"
    volumes:
    - db-data:/var/lib/mysql
  web:
    #build: .docker/rails/
    image: rubyonrails_amemiya:20190414
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rdebug-ide --host 0.0.0.0 --port 1234 --dispatcher-port 26162 -- bin/rails s"
    ports:
    - "3000:3000"
    - "1234:1234"
    volumes:
    - .:/myapp
    environment:
      RAILS_ENV: development
    env_file: .env.dev
    depends_on:
    - db
    stdin_open: true
    tty: true
volumes:
  db-data:
    external: true
